modLoader = "javafml"
loaderVersion = "[1,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "endemic"
version = "${version}"
displayName = "Endemic"
displayTest = "IGNORE_SERVER_VERSION"
displayURL = "https://github.com/yurisuika/Endemic"
issueTrackerURL = "https://github.com/yurisuika/Endemic/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Harness the ability to grow any tree from a sapling!
'''

[[mixins]]
config = "endemic.mixins.json"

[[dependencies.endemic]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.endemic]]
modId = "neoforge"
type = "required"
versionRange = "[20.5,21)"
ordering = "NONE"
side = "BOTH"